config/routes.rb
Rails.application.routes.draw do
  
  get 'find_csa/all_boxes'
  get 'find_csa/all_farms'
  get 'find_csa/filter_search'
  post 'add_to_cart' => 'cart#add_to_cart'
  get 'view_order' => 'cart#view_order'
  post 'checkout' => 'cart#checkout'
  get 'all_boxes' => 'find_csa#all_boxes'
  get 'all_farms' => 'find_csa#all_farms'
  get 'filter' => 'find_csa#filter_search'
  post 'order_complete' => 'cart#order_complete'

  post 'like' => 'shared#view_likes'
  get 'view_likes' => 'shared#view_likes'

  resources :boxes do
  resource :like
  end

  resources :orders
  resources :line_items
  devise_for :users
  resources :boxes
  resources :farms

  root to: 'farms#home'

end

app/models/farm.rb
class Farm < ActiveRecord::Base
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  	
	has_many :boxes
	has_many :likes
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  before_action :set_farm, only: [:show, :edit, :update, :destroy]

  # GET /farms
  # GET /farms.json
  def index
    @farms = Farm.all
  end

  # GET /farms/1
  # GET /farms/1.json
  def show
  end

  # GET /farms/new
  def new
    @farm = Farm.new
  end

  # GET /farms/1/edit
  def edit
  end

  # POST /farms
  # POST /farms.json
  def create
    @farm = Farm.new(farm_params)

    respond_to do |format|
      if @farm.save
        format.html { redirect_to @farm, notice: 'Farm was successfully created.' }
        format.json { render :show, status: :created, location: @farm }
      else
        format.html { render :new }
        format.json { render json: @farm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /farms/1
  # PATCH/PUT /farms/1.json
  def update
    respond_to do |format|
      if @farm.update(farm_params)
        format.html { redirect_to @farm, notice: 'Farm was successfully updated.' }
        format.json { render :show, status: :ok, location: @farm }
      else
        format.html { render :edit }
        format.json { render json: @farm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /farms/1
  # DELETE /farms/1.json
  def destroy
    @farm.destroy
    respond_to do |format|
      format.html { redirect_to farms_url, notice: 'Farm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_farm
      @farm = Farm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def farm_params
      params.require(:farm).permit(:name, :address, :city, :state, :zip, :email, :phone_number, :fb_url, :instagram_url, :website, :bio, :owner, :video_url, :practices_followed, :image)
    end
end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/views/farms/_form.html.erb
<%= form_for(@farm) do |f| %>
  <% if @farm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@farm.errors.count, "error") %> prohibited this farm from being saved:</h2>

      <ul>
      <% @farm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :fb_url %><br>
    <%= f.text_field :fb_url %>
  </div>
  <div class="field">
    <%= f.label :instagram_url %><br>
    <%= f.text_field :instagram_url %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :owner %><br>
    <%= f.text_field :owner %>
  </div>
  <div class="field">
    <%= f.label :video_url %><br>
    <%= f.text_field :video_url %>
  </div>
  <div class="field">
    <%= f.label :practices_followed %><br>
    <%= f.text_field :practices_followed %>
  </div>
  <div class="field">
    <strong>Upload Profile Image: </strong><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/farms/edit.html.erb
<h1>Editing Farm</h1>

<%= render 'form' %>

<%= link_to 'Show', @farm %> |
<%= link_to 'Back', farms_path %>

app/views/farms/home.html.erb
<section id="hero">
	<div class="container-fluid">
		<div class="row">

			<div class="col-md-4 hero-img-left">
				<div class="hero-content">
					<h2>Healthy Planet</h2>
					<p>Local food production is also local distribution. Ensuring a smaller footprint on transporation and better practices on the land.</p>
				</div>
			</div>

			<div class="col-md-4 hero-img-mid">
				<div class="hero-content">
					<h2>Healthy Food</h2>
					<p>Local produce is little to no processing or preserving, so all flavor and vitamins stay rich, vibrant and nutritious.</p>
				</div>
			</div>

			<div class="col-md-4 hero-img-right">
				<div class="hero-content">
					<h2>Healthy Communities</h2>
					<p>Buying your food from local growers contributes to a stronger local economy, so all community members can live a higher quality of life.</p>
				</div>
			</div>

		</div>
	</div>
</section>

<section id="action-row">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<div class="home-action">
					<h3>Community Supported Agriculture (CSA) is a way for consumers to buy local, seasonal produce directly from a farmer in their community.</h3>
					<button class="btn btn-lg btn-danger"><%= link_to 'Find Your CSA' %></button>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="explained">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<h1>How It Works</h1>
			</div>
		</div>

		<div class="col-md-4">
			<br>
			<h2><i class="glyphicon glyphicon-search"></i> Find a CSA</h2>
			<p>Use Tomato to look at all the Community Agruculture Shares available to you in your area. It is easy. <a href="">Click here</a> to view all the CSA's to choose from! Search by content, location, farm practice, length of season, or produce variety. </p>
		</div>

		<div class="col-md-4">
			<br>
			<h2><i class="glyphicon glyphicon-pencil"></i> Sign Up!</h2>
			<p>When you find the perfect CSA offered by a great farm add to your basket. Check out and provide the necessary details to the farm like your preferred pick-up location or share size. The form is easy and you can pay for your share online... it goes right to the farm!</p>
		</div>

		<div class="col-md-4">
			<br>
			<h2><i class="glyphicon glyphicon-apple"></i> Pick up your Share!</h2>
			<p>Every farm has different features they offer. Often you will find that farms will deliver CSAs to farmer's markets or other venues each week. Pick it up and start cooking! Enjoy.</p>
		</div>
	</div>
</section>

app/views/farms/index.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<h1>Farms Love</h1>


<div class="row">
  <% @farms.each do |farm| %>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <div style="width: 100%;">
            <%= image_tag farm.image.url(), class: "img-responsive" %>
          </div>
          <br>
          <h1><%= farm.name %></h1>
          <h4>Address: <%= farm.address %><br><%= farm.city %>, <%= farm.state %> <%= farm.zip %></h4><br>
          <h4>Contact: <%= farm.phone_number %> | <%= farm.email %> </h4>
          <h4>Social: <%= farm.fb_url %> | <%= farm.instagram_url %> | <%= farm.website %> </h4>
          <br>

          <p><%= farm.owner %><strong></strong><%= farm.bio %></p>
          <p><strong>We Practice:</strong> <%= farm.practices_followed %></p>
          <hr>
          <%= link_to 'View Profile', farm %> | <%= link_to 'Edit', edit_farm_path(farm) %> | <%= link_to 'Destroy', farm, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<br>

<%= link_to 'New Farm', new_farm_path %>

</div>

app/views/farms/new.html.erb
<h1>New Farm</h1>

<%= render 'form' %>

<%= link_to 'Back', farms_path %>

app/views/farms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @farm.image.url(:medium) %>
</p>

<p>
  <strong>Name:</strong>
  <%= @farm.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @farm.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @farm.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @farm.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @farm.zip %>
</p>

<p>
  <strong>Email:</strong>
  <%= @farm.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @farm.phone_number %>
</p>

<p>
  <strong>Fb url:</strong>
  <%= @farm.fb_url %>
</p>

<p>
  <strong>Instagram url:</strong>
  <%= @farm.instagram_url %>
</p>

<p>
  <strong>Website:</strong>
  <%= @farm.website %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @farm.bio %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @farm.owner %>
</p>

<p>
  <strong>Video url:</strong>
  <%= @farm.video_url %>
</p>

<p>
  <strong>Practices followed:</strong>
  <%= @farm.practices_followed %>
</p>

<%= link_to 'Edit', edit_farm_path(@farm) %> |
<%= link_to 'Back', farms_path %>