config/routes.rb
Rails.application.routes.draw do
  
  get 'find_csa/all_boxes'
  get 'find_csa/all_farms'
  get 'find_csa/filter_search'
  post 'add_to_cart' => 'cart#add_to_cart'
  get 'view_order' => 'cart#view_order'
  post 'checkout' => 'cart#checkout'
  get 'all_boxes' => 'find_csa#all_boxes'
  get 'all_farms' => 'find_csa#all_farms'
  get 'filter' => 'find_csa#filter_search'
  post 'order_complete' => 'cart#order_complete'

  post 'like' => 'shared#view_likes'
  get 'view_likes' => 'shared#view_likes'

  resources :boxes do
  resource :like
  end

  resources :orders
  resources :line_items
  devise_for :users
  resources :boxes
  resources :farms

  root to: 'farms#home'

end

app/models/box.rb
class Box < ActiveRecord::Base
	belongs_to :farm
	has_many :likes
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :set_box, only: [:show, :edit, :update, :destroy]

  # GET /boxes
  # GET /boxes.json
  def index
    @boxes = Box.all

    @search = Box.search(params[:q])
    @boxes = @search.result
<<<<<<< HEAD
=======

>>>>>>> 7dca33372affa9d0d1b147afe8164324d2120473
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
    @likes = Like.all
  end

  # GET /boxes/new
  def new
    @box = Box.new
    @farms = Farm.all
  end

  # GET /boxes/1/edit
  def edit
     @farms = Farm.all
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @box = Box.new(box_params)
     @farms = Farm.all
     
    respond_to do |format|
      if @box.save
        format.html { redirect_to @box, notice: 'Box was successfully created.' }
        format.json { render :show, status: :created, location: @box }
      else
        format.html { render :new }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boxes/1
  # PATCH/PUT /boxes/1.json
  def update
    respond_to do |format|
      if @box.update(box_params)
        format.html { redirect_to @box, notice: 'Box was successfully updated.' }
        format.json { render :show, status: :ok, location: @box }
      else
        format.html { render :edit }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @box.destroy
    respond_to do |format|
      format.html { redirect_to boxes_url, notice: 'Box was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box
      @box = Box.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def box_params
      params.require(:box).permit(:name, :contents, :description, :price, :length_of_time, :start_date, :end_date, :farm_id, :pickup_location)
    end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/boxes/_form.html.erb
<%= form_for(@box) do |f| %>
  <% if @box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@box.errors.count, "error") %> prohibited this box from being saved:</h2>

      <ul>
      <% @box.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<<<<<<< HEAD
  <%= simple_form_for(@box) do |f| %>

  <%= f.input :farm %>
  <%= f.input :name %>
  <%= f.input :contents %>
  <%= f.text_area :description %>

  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.input :length_of_time, hint: "Length is in weeks of Share" %>

  <%= f.input :price, hint: "Price is per season" %>
  <%= f.input :size, hint: "Recommended household size" %>
  <%= f.input :weight, hint: "Expected weight of produce per week" %>

  <%= f.input :pickup_location, hint: "List the areas where your farm delivers" %>
  
  <%= f.button :submit %>

<% end %>
=======
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :contents %><br>
    <%= f.text_field :contents %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :length_of_time %><br>
    <%= f.number_field :length_of_time %>
  </div>
  <div class="field">
    <%= f.label :household_size %><br>
    <%= f.number_field :size %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.select(:farm_id, @farms.collect {|f| [f.name, f.id]}, {include_blank: "Choose a farm" }) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
>>>>>>> 7dca33372affa9d0d1b147afe8164324d2120473
<% end %>

app/views/boxes/edit.html.erb
<div class="container">

<h1>Editing Box</h1>

<%= render 'form' %>

<%= link_to 'Show', @box %> |
<%= link_to 'Back', boxes_path %>
</div>

app/views/boxes/filter_search.html.erb
<h1>Find a CSA!</h1>

<h3>You can search shares in the area by different requests.</h3>

<% content_for :search do %>
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<%= search_form_for @search do |f| %>
				<%= f.text_field :contents_cont, class: "radius-left expand", placeholder: "Contains this type of Produce" %>
			</div>
		</div>

		<div class="row">
			<div class="col-md-8">
				<% f.submit "Find a CSA", class: "btn btn-lg btn-danger" %>
			</div>
		</div>
		<% end %>
		<% end %>
	</div>

app/views/boxes/index.html.erb
<p id="notice"><%= notice %></p>

<section id="csasearch">
  <div class="container">
    <div class="row">
      <div class="col-md-10">
        <h1>Find a CSA!</h1>
<<<<<<< HEAD
        <h3>You can search shares in the area by different requests.</h3>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-md-10">
        <div class="form-group">
          <p>Search by Contents</p>
          <%= search_form_for @search do |f| %>
          <%= f.text_field :contents_cont, placeholder: "Content contains" %>
          <%= f.submit "Search for CSA", class: "btn btn-default" %>
          <% end %>
        </div>
        <div class="form-group">
           <p>Search by Price</p>
          <%= search_form_for @search do |f| %>
          <%= f.text_field :price_gteq, placeholder: "Price between" %>
          <%= f.text_field :price_lteq, placeholder: "and" %>
          <%= f.submit "Search for CSA", class: "btn btn-default" %>
          <% end %>
        </div>
        <div class="form-group">
           <p>Search by Pickup Locations</p>
          <%= search_form_for @search do |f| %>
          <%= f.text_field :pickup_location_cont, placeholder: "Enter a farmer market nearby" %>
          <%= f.submit "Search for CSA", class: "btn btn-default" %>
          <% end %>
        </div>
       </div>
    </div>
  </div>
</section>

=======

        <h3>You can search shares in the area by different requests.</h3>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-md-10">
        <div class="form-group">
          <p>Search by Contents</p>
          <%= search_form_for @search do |f| %>
          <%= f.text_field :contents_cont, placeholder: "Content contains" %>
          <%= f.submit "Search for CSA", class: "btn btn-default" %>
          <% end %>
        </div>
        <div class="form-group">
           <p>Search by Price</p>
          <%= search_form_for @search do |f| %>
          <%= f.text_field :price_gteq, placeholder: "Price between" %>
          <%= f.text_field :price_lteq, placeholder: "and" %>
          <%= f.submit "Search for CSA", class: "btn btn-default" %>
          <% end %>
        </div>
        <div class="form-group">
           <p>Search by Pickup Locations</p>
          <%= search_form_for @search do |f| %>
          <%= f.text_field :pickup_location_cont, placeholder: "Enter a farmer market nearby" %>
          <%= f.submit "Search for CSA", class: "btn btn-default" %>
          <% end %>
        </div>
       </div>
    </div>
  </div>
</section>

>>>>>>> 7dca33372affa9d0d1b147afe8164324d2120473
<section id="csa-results">
    <% @boxes.each do |box| %>
    <div class="container box-listing">
    <div class="row">
<<<<<<< HEAD
      <div class="col-sm-8">
      <div class="farm-name">
        <h3><strong><%= box.farm.name %></strong></h3>
        <p><%= box.name %></p>
      </div>
      </div>
=======
      <div class="farm-name">
        <h3><strong><%= box.farm_id %></strong></h3>
        <p><%= box.name %></p>
      </div>
>>>>>>> 7dca33372affa9d0d1b147afe8164324d2120473
    </div>
    <div class="row">
      <div class="col-sm-4">
        <p><strong>Contains:</strong> <%= box.contents %></p>
        <p><strong>About:</strong> <%= box.description %></p>
      </div>
      <div class="col-sm-4">
<<<<<<< HEAD
        <p><strong>Share Starts:</strong> <%= box.start_date.strftime("%B %e, %Y") %></p> <p><strong>Share Ends:</strong> <%= box.end_date.strftime("%B %e, %Y") %></p>
        <p><strong>Total Weeks: <%= box.length_of_time %></strong></p>
        <p><strong>Feeds household size:</strong> <%= box.size %></p>
        <p><strong>Average produce weight:</strong> <%= box.weight %></p>

      </div>
      <div class="col-sm-4">
        <p><strong>Pickup Locations:</strong> <%= box.pickup_location %></p>
        <h3>$<%= box.price %></h3><br>
        
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
      <p class="pull-right"><%= link_to 'Show', box %> | <%= link_to 'Edit', edit_box_path(box) %> | <%= link_to 'Destroy', box, method: :delete, data: { confirm: 'Are you sure?' } %>  

        <%= form_tag('/add_to_cart') do %> 
        <%= submit_tag "Add To Favorite", class: "btn btn-info" %>
      </p>
        <% end %> 
    </div>
=======
        <p><strong>Share Starts:</strong> <%= box.start_date %></p> <p><strong>Share Ends:</strong><%= box.end_date %></p>
        <p><strong>Total Weeks: <%= box.length_of_time %></strong></p>
      </div>
      <div class="col-sm-4">
        <h3>$<%= box.price %></h3><br>
        <p><strong>Feeds household size:</strong> <%= box.size %></p>
        <p><strong>Average produce weight:</strong> <%= box.weight %></p>
      </div>
    </div>
    <div class="row">
      <p><%= link_to 'Show', box %> | <%= link_to 'Edit', edit_box_path(box) %> | <%= link_to 'Destroy', box, method: :delete, data: { confirm: 'Are you sure?' } %></p>
>>>>>>> 7dca33372affa9d0d1b147afe8164324d2120473
    </div>
  </div>
<% end %>
</section>

<br>

<%= link_to 'New Box', new_box_path %>

app/views/boxes/new.html.erb
<div class="container">

<<<<<<< HEAD
<h1>List a New Share</h1>
=======
<h1>List a new CSA Share</h1>
>>>>>>> 7dca33372affa9d0d1b147afe8164324d2120473

<%= render 'form' %>

<%= link_to 'Back', boxes_path %>

<<<<<<< HEAD
</div>
=======
</div>
>>>>>>> 7dca33372affa9d0d1b147afe8164324d2120473

app/views/boxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @box.name %>
</p>

<p>
  <strong>Contents:</strong>
  <%= @box.contents %>
</p>

<p>
  <strong>Description:</strong>
  <%= @box.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @box.price %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @box.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @box.end_date %>
</p>

<p>
  <strong>Length of time:</strong>
  <%= @box.length_of_time %>
</p>

<p>
  <strong>Length of time:</strong>
  <%= @box.size %>
</p>
<p>
  <strong>Length of time:</strong>
  <%= @box.weight %>
</p>


<p>
  <strong>Farm:</strong>
  <%= @box.farm.name %>
</p>

<%= render 'shared/likes' %>

<p>
  <%= form_tag('/add_to_cart') do %>
    <div class="cant-see-me">
      <%= number_field_tag :box_id, @box.id %>
    </div>
   
    <%= submit_tag "Add To Favorite", class: "btn btn-info" %>
  <% end %>
</p>

<%= link_to 'Edit', edit_box_path(@box) %> |
<%= link_to 'Back', boxes_path %>